spring:
  application:
    name: lottolearn-auth
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://api.lottolearn.com/login/oauth2/code/{registrationId}
          weibo:
            client-id: ${WEIBO_APP_KEY}
            client-secret: ${WEIBO_APP_SECRET}
            redirect-uri: https://api.lottolearn.com/login/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
        provider:
          weibo:
            authorization-uri: https://api.weibo.com/oauth2/authorize
            token-uri: https://api.weibo.com/oauth2/access_token
            user-info-uri: https://api.weibo.com/2/users/show.json
            user-name-attribute: id
  redis:
    host: localhost
    port: 6379
server:
  port: 51200
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
lottolearn:
  auth:
    key-store-dir: ${KEY_STORE_DIR:/tmp/lottolearn/keys}
