spring:
  application:
    name: lottolearn-auth
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://api.lottolearn.com/login/oauth2/code/{registrationId}
  redis:
    host: localhost
    port: 6379
server:
  port: 51200
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
