spring:
  application:
    name: lottolearn-processor
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
server:
  port: 51209
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
lottolearn:
  media:
    base-url: https://media.lottolearn.com
