spring:
  application:
    name: lottolearn-processor
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
server:
  port: 51209
dubbo:
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://registry.lottolearn.com:80
lottolearn:
  media:
    base-url: https://media.lottolearn.com
