spring:
  application:
    name: lottolearn-message
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lottolearn.com
          jwk-set-uri: http://localhost:51200/.well-known/jwks.json
server:
  port: 51218
dubbo:
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://registry.lottolearn.com:80
