spring:
  application:
    name: lottolearn-message
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:websocket
    username: ${H2_USERNAME:ws}
    password: ${H2_PASSWORD:ws}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lottolearn.com
          jwk-set-uri: http://auth.lottolearn.com:51200/.well-known/jwks.json
  jackson:
    time-zone: GMT+8
server:
  port: 51218
dubbo:
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://registry.lottolearn.com:8868
