spring:
  application:
    name: lottolearn-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///lottolearn_course?characterEncoding=UTF-8&serverTimezone=Hongkong
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      async-init: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
  jpa:
    open-in-view: false
  jackson:
    time-zone: GMT+8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lottolearn.com
          jwk-set-uri: http://localhost:51200/.well-known/jwks.json
server:
  port: 51203
dubbo:
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://registry.lottolearn.com:80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
