spring:
  application:
    name: lottolearn-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///lottolearn_course?characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      async-init: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lottolearn.com
          jwk-set-uri: http://localhost:51200/.well-known/jwks.json
server:
  port: 51203
logging:
  level:
    root: warn
dubbo:
  scan:
    base-packages:
      - xo.fredtan.lottolearn.api
      - xo.fredtan.lottolearn.course.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
mybatis:
  configuration:
    map-underscore-to-camel-case: true