spring:
  application:
    name: lottolearn-storage
  servlet:
    multipart:
      max-request-size: 4GB
  rabbitmq:
    host: mq.lottolearn.com
    port: ${RABBITMQ_PORT:5672}
    virtual-host: /
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lottolearn.com
          jwk-set-uri: http://auth.lottolearn.com:51200/.well-known/jwks.json
  jackson:
    time-zone: GMT+8
server:
  port: 51206
dubbo:
  provider:
    version: 1.0.0
  consumer:
    version: 1.0.0
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://registry.lottolearn.com:8868
lottolearn:
  storage:
    base-path: ${STORAGE_BASE_PATH:/tmp/lottolearn/storage}
    base-url: https://storage.lottolearn.com
  media:
    base-path: ${MEDIA_BASE_PATH:/tmp/lottolearn/media}
