spring:
  application:
    name: lottolearn-storage
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
server:
  port: 51206
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
lottolearn:
  storage:
    base-path: ${STORAGE_BASE_PATH:/tmp/lottolearn/storage}
    base-url: https://storage.lottolearn.com
  media:
    base-path: ${MEDIA_BASE_PATH:/tmp/lottolearn/media}
